### ISSUE TITLE
Provide health check in Dockerfile

### ISSUE THREAD

**Issue by zbigniew-malcherczyk-tg** [splitio/split-synchronizer#284]
Currently the Dockerfile does not provide the healtcheck even though the split-synchronizer contains multiple health endpoints.

**Comment by sanzmauro** [comment]
Hi @zbigniew-malcherczyk-tg 

Could you provide more details on what you mean by "Dockerfile does not provide the health check"? 

Additionally, for context, we expose port 3010 for the admin dashboard. You can configure this in your deployment as follows:
```
ports:
  - name: dashboard
    containerPort: 3010
startupProbe:
  httpGet:
    port: dashboard
    path: /health/dependencies
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  httpGet:
    port: dashboard
    path: /health/application
  timeoutSeconds: 5
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
```
